### ISSUE TITLE
Add __init__.py for ex1_linan_2023, cstr and small_batch

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/gdplib#53]
The `__init__.py` file is missing in the `ex1_linan_2023`, `cstr` and `small_batch` subfolder.

**Comment by AlbertLee125** [comment]
I will make the ```__init__.py``` in the file.

**Comment by ZedongPeng** [comment]
Could you also check each subfolder and see if the `__init__.py` file is missing?
